version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202201-01

    steps:
      - checkout
      - run: echo "Your build commands go here"

workflows:
  version: 2
  build:
    jobs:
      - build